version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/action
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: server/scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: server/scripts/start.sh
      timeout: 60
      runas: ubuntu