# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  S3_CLIENT_BUCKET_NAME: padakmon-client-bucket

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install modules
      run: npm install
      working-directory: ${{ env.working-directory }}
      
    - name: Build project
      run: npm run build
      working-directory: ${{ env.working-directory }}
      
    - name: Deploy
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://$S3_CLIENT_BUCKET_NAME
        
        

